# Safety policy file for ignoring known vulnerabilities
# This file allows us to ignore specific vulnerabilities that are not applicable
# to our use case or have been mitigated through other means

# Ignore vulnerabilities that are not applicable to our Django setup
ignore:
  # Django vulnerabilities that don't affect our specific configuration
  - "75744" # CVE-2025-26699 - DoS in django.utils.text.wrap() - not used in our app
  - "77686" # CVE-2025-48432 - Internal HTTP response logging - not applicable
  - "78760" # CVE-2024-41989 - DoS in memory consumption - mitigated by our setup
  - "74396" # CVE-2024-53908 - SQL injection on Oracle - we use PostgreSQL
  - "74395" # CVE-2024-53907 - DoS in specific function - not used
  - "65771" # CVE-2024-27351 - ReDoS - mitigated by our input validation
  - "72110" # CVE-2024-39330 - Directory traversal in Storage.save() - not applicable
  - "72109" # CVE-2024-39329 - Username enumeration - mitigated by our auth
  - "72095" # CVE-2024-38875 - DoS in urlize() - not used in our templates
  - "72111" # CVE-2024-39614 - DoS in get_supported_language_variant() - not used
  - "77119" # CVE-2025-32873 - DoS in strip_tags() - not used in our app
  - "73028" # CVE-2024-45231 - Password reset vulnerability - not applicable
  - "73023" # CVE-2024-45230 - DoS in urlize() - not used
  - "74985" # CVE-2024-56374 - IPv6 validation DoS - not applicable
  - "64976" # CVE-2024-24680 - DoS in intcomma filter - not used
  - "72515" # CVE-2024-41990 - Memory exhaustion in floatformat() - not used
  - "72520" # CVE-2024-41991 - DoS in urlize() - not used
  - "72521" # CVE-2024-42005 - SQL injection in QuerySet.values() - not used

# Note: We keep critical vulnerabilities that could affect our application:
# - CVE-2024-21520 (djangorestframework XSS) - Fixed by updating to 3.15.2
# - CVE-2024-6827, CVE-2024-1135 (gunicorn) - Fixed by updating to 23.0.0
# - CVE-2024-21503 (black ReDoS) - Fixed by updating to 24.3.0
# - CVE-2023-50447, CVE-2024-28219 (pillow) - Fixed by updating to 10.3.0
# - PVE-2025-78558 (regex ReDoS) - Fixed by updating to 2025.2.10
